{
 "title": "Capteurs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Luminosité salle B106",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lumens" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "illumination",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "building::tag", "operator": "=", "value": "INFO" },
      { "condition": "AND", "key": "room::tag", "operator": "=", "value": "B106" }
     ]
    }
   ]
  },
  {
   "title": "Température salle B101",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "building::tag", "operator": "=", "value": "INFO" },
      { "condition": "AND", "key": "room::tag", "operator": "=", "value": "B101" }
     ]
    }
   ]
  },
  {
   "title": "Luminosité salle E105",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "lumens" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "illumination",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "building", "operator": "=", "value": "RT" },
      { "condition": "AND", "key": "room", "operator": "=", "value": "E105" }
     ]
    }
   ]
  },
  {
   "title": "Température salle E100",
   "type": "timeseries",
   "description": "Données du capteur température de la salle E100",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE \"building\" = 'RT' AND \"room\" = '",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "building", "operator": "=", "value": "RT" },
      { "condition": "AND", "key": "room", "operator": "=", "value": "E100" }
     ]
    }
   ]
  }
 ]
}